### PR TITLE
support for parsing single event in EPCIS JSON document

### PR DESCRIPTION
**Pull request by dakbhavesh**
Hi @Echsecutor,

As per latest updates in openapi.yml, added support to parse single event contained epcis json document.

### CODE REVIEW

**Comment by dakbhavesh** [comment]
Hi @Echsecutor, Just a friendly reminder, please take a look at this PR and let me know if you have any review comments.

**Comment by dakbhavesh** [comment]
Hi @RalphTro, This branch can also be merged as it has no impact on any existing feature and it will be a useful feature to support a single EPCIS event in JSON format.

**Comment by RalphTro** [comment]
Dear @dakbhavesh ,
Thanks! I just had a look into this and it worked when I run our script via the command line tool for the event you added ("python3 epcis_event_hash_generator/main.py -p tests/examples/epcisDocWithSingleEvent.json")

I noticed the same bug your other PR is about (i.e. that eventID is to be ignored). Will have a look into this soon as well.

eventType=ObjectEventeventTime=2005-04-04T02:33:31.116ZeventTimeZoneOffset=-06:00epcListepc=urn:epc:id:sgtin:0614141.107346.2017epc=urn:epc:id:sgtin:0614141.107346.2018action=OBSERVEbizStep=https://ns.gs1.org/voc/Bizstep-shippingdisposition=https://ns.gs1.org/voc/Disp-in_transitreadPointid=urn:epc:id:sgln:0614141.07346.1234bizTransactionListbizTransaction=http://transaction.acme.com/po/12345678type=https://ns.gs1.org/voc/BTT-poeventID=_:event1

**Comment by dakbhavesh** [comment]
Dear @RalphTro, I have fixed the trivial issue. Just needed to update the hash and prehash for a single event example.  Pushed changed directly to master as it was pretty straightforward.

**Comment by Echsecutor** [comment]
@dakbhavesh sorry for not looking into this due to time constraints. @RalphTro many thanks for taking over!

**Pull request merged**
